resource_group_name = "mysqldb-test"
primary_location = "eastus2"
secondary_location = "centralus"
db_version="12.0"
environment="poc"
vault="mysqldb-test-kv"
sqlserver-name="mysqldb-test-mssqlserver"